# TODO comment this workflow
name: Run Actions
on:
  push:
  workflow_call:
jobs:
  runs-using-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sfeir-open-source/sfeir-school-github-action-dev/.github/actions/runs-using-node@v1
      - uses: sfeir-open-source/sfeir-school-github-action-dev/.github/actions/runs-using-docker@v1
      - uses: ./.github/actions/runs-using-composite

  summary-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/summary-composite

  message-commands:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::debug::a debug message"
          echo "::notice::a notice message"
          echo "::warning::a warning message"
          echo "::error::an error message"

  message-file-commands:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::notice file=LICENCE,line=1,endLine=2,title=Notice Title::a notice message"
          echo "::warning file=LICENCE,line=1,endLine=2,title=Warning Title::a warning message"
          echo "::error file=LICENCE,line=1,endLine=2,title=Error Title::an error message"
